<a href="https://colab.research.google.com/github/Rohit-1311/DataScienceS3/blob/main/Rohit_StudentCopy_of_CO1_NumpyArray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# program to create an array of all the even integers from 20 to 80
import numpy as np
array=np.arange(20,80,2)
print(array)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]


In [25]:
#Write a program to create a numpy array and perform element-wise comparison (greater, greater_equal, less than, lesser_equal).
import numpy as py
x = np.array([2, 5, 18, 14, 55])
y = np.array([3, 25, 10, 43, 21])

print(x)
print(y)

print("\nGreater than")
print(np.greater(x,y))

print("\nGreater_Equal")
print(np.greater_equal(x,y))

print("\nLess than")
print(np.less(x,y))

print("\nLesser Equal")
print(np.less_equal(x,y))

[ 2  5 18 14 55]
[ 3 25 10 43 21]

Greater than
[False False  True False  True]

Greater_Equal
[False False  True False  True]

Less than
[ True  True False  True False]

Lesser Equal
[ True  True False  True False]


In [20]:
#program to multiply two given arrays of same size
import numpy as py
x = np.array([2, 5, 18, 14, 55])
y = np.array([3, 25, 10, 43, 21])
m=np.multiply(x,y)
print(m)

[   6  125  180  602 1155]


In [23]:
#Program to save a given array to a text file and load it
import numpy as np
import os
x=np.arange(16).reshape(4,4)
print(x)
h='Cl1 Cl2 Cl3 Cl4'
np.savetxt('myarray.txt',x,fmt="%d",header=h)
print("Afer loading Content")
print(np.loadtxt("myarray.txt"))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Afer loading Content
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
